services:
  webui:
    image: docker.io/razzabi/participant-webui:v0.2.1
    container_name: ${PARTICIPANT_NAME}.credentials-webui
    restart: always
    environment:
      BASE_URL: https://${PARTICIPANT_NAME}.${DOMAIN_NAME}
      API_BASE_URL: "https://${PARTICIPANT_NAME}.${DOMAIN_NAME}/api/v1/"
      PARTICIPANT_NAME: ${PARTICIPANT_NAME}
    networks:
      - datacellar

networks:
  datacellar:
    external: true
    name: datacellar_network
