
services:

  connector:
    image: datacellar/edc:ctic
    container_name: ${PARTICIPANT_NAME}.connector
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CLEAN: "${CLEAN:-true}"   
        SSI: "${SSI:-false}"      
    environment:
      ORG_GRADLE_PROJECT_useSSI: "${SSI:-false}"
    # ports:
      # - 29191:${EDC_CONNECTOR_API_PORT}
      # - 29192:${EDC_CONNECTOR_CONTROL_PORT}
      # - 29193:${EDC_CONNECTOR_MANAGEMENT_PORT}
      # - 29194:${EDC_CONNECTOR_PROTOCOL_PORT}
      # - 29291:${EDC_CONNECTOR_PUBLIC_PORT}
    volumes:
      - ./certs:/opt/src/certs
      - ./config:/opt/src/config
      - ./connector:/opt/src/connector
    command:
      [
        java,
        -Dedc.fs.config=/opt/src/config/connector.properties,
        -Dedc.keystore=/opt/src/certs/cert.pfx,
        -Dedc.keystore.password=datacellar,
        -Dedc.vault=/opt/src/certs/vault.properties,
        -jar,
        /opt/src/connector/openapi-connector/build/libs/openapi-connector.jar,
      ]
    networks:
      - datacellar





networks:
  datacellar:
    driver: bridge
    name: datacellar_network
    ipam:
     config:
       - subnet: 192.168.0.0/24
         gateway: 192.168.0.1
    driver_opts:
      com.docker.network.bridge.name: br_datacellar