version: "3"

tasks:
  config:
    desc: "Replace the environment variables in the connector properties file template"
    cmds:
      - >
        envsubst
        < {{.TASKFILE_DIR}}/config/connector.properties.tmpl
        > {{.TASKFILE_DIR}}/config/connector.properties
      # Remove lines where property value is empty
      - sed -i '/=$/d' {{.TASKFILE_DIR}}/config/connector.properties

  start:
    desc: "Start the connector stack"
    deps:
      - config
    cmds:
      - docker compose -f {{.TASKFILE_DIR}}/docker-compose.yml up -d --wait

  stop:
    desc: "Stop the connector stack"
    cmds:
      - docker compose -f {{.TASKFILE_DIR}}/docker-compose.yml down
