---
#-------------------------------------------------------------------
# authors     [ Radhouene AZZABI ]
# contacts    [ azzabi.radhouene@cea.fr ]
# created     2024/10-15T12:12:24
# modified    2024/10-15T12:12:24
# version     1.0.0
#-------------------------------------------------------------------

version: "3"

tasks:
  start-proxy:
    desc: "Start the reverse proxy"
    cmds:
      - docker compose -f ./reverse-proxy/docker-compose.yml up -d --wait

  setup-participant:
    desc: "Create a Data Cellar Dataspace participant"
    silent: true
    env:
      USER_WORKING_DIR: "{{.USER_WORKING_DIR}}"
    cmds:
      - "{{.ROOT_DIR}}/setup-participant.sh"
