services:
  wallet:
    image: waltid/wallet-api:${WALTID_IMG_VERSION}
    container_name: ${PARTICIPANT_NAME}.wallet
    restart: unless-stopped
    volumes:
      - ./waltid/config:/waltid-wallet-api/config
      - wallet_data:/waltid-wallet-api/data
    # ports:
    #   - 7001:7001
    networks:
      - datacellar
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7001/swagger/index.html"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  wallet_data: {}

networks:
  datacellar:
    external: true
    name: datacellar_network
