#-------------------------------------------------------------------
# authors     [ Radhouene AZZABI ]
# contacts    [ azzabi.radhouene@cea.fr ]
# created     2024-10-15 12:36:03
# modified    2024-10-15 12:35:49
# version     1.0.0
#-------------------------------------------------------------------

version: "3"

# dotenv: ['../.env'] # uncomment if you want to test tasks localy

tasks:
  start:
    desc: "Start Wallet"
    silent: true
    deps:
      - config
    preconditions:
      - test -f {{.TASKFILE_DIR}}/docker-compose.yml
    cmds:
      - docker compose -p {{.PARTICIPANT_NAME}} -f {{.TASKFILE_DIR}}/docker-compose.yml up wallet -d --wait
  
  stop:
    desc: "Stop Wallet"
    silent: true
    preconditions:
      - test -f {{.TASKFILE_DIR}}/docker-compose.yml
    cmds:
        - docker compose -p {{.PARTICIPANT_NAME}} -f {{.TASKFILE_DIR}}/docker-compose.yml down wallet
  
  config:
    desc: "Config Wallet"
    silent: true
    dir: '{{.WALLET_FOLDER}}/waltid'
    cmds:
      - sudo chmod 755 data && sudo chown -R 1001:1001 data

  upgrade:
    desc: "Upgrade the wallet"
    silent: true
    preconditions:
      - test -f {{.TASKFILE_DIR}}/docker-compose.yml
    cmds:
      - docker compose -p {{.PARTICIPANT_NAME}} -f {{.TASKFILE_DIR}}/docker-compose.yml pull --ignore-pull-failures --quiet --policy always