#-------------------------------------------------------------------
# authors     [ Michael Vassiliadis ]
# contacts    [ m.vassiliadis@que-tech.com ]
# created     2025/03-14T10:00:00 
# modified    2025/03-14T10:00:00 
# version     1.0.0
#-------------------------------------------------------------------

version: "3"

# dotenv: ['../.env']

tasks:
  prepare:
    desc: "Load the cde-server Docker image to the engine"
    dir: '{{.TASKFILE_DIR}}'
    cmds: 
      - |
        # Start Fuseki service
        docker compose -p {{.PARTICIPANT_NAME}} -f {{.TASKFILE_DIR}}/docker-compose.yml up fuseki -d
       
        # Create auth header once
        AUTH_HEADER="Authorization: Basic $(echo -n "{{.CDE_FUSEKI_USER}}:{{.CDE_FUSEKI_PASSWORD}}" | base64)"

        # Check if dataset exists
        echo "Checking if dataset {{.CDE_FUSEKI_DATASET}} exists..."
        DATASET_EXISTS=$(curl -s -X GET \
          -H "$AUTH_HEADER" \
          "http://localhost:3030/$/datasets" | grep -c "{{.CDE_FUSEKI_DATASET}}" || true)

        if [ "$DATASET_EXISTS" -gt 0 ]; then
          echo "Dataset {{.CDE_FUSEKI_DATASET}} already exists, skipping creation"
        else
          echo "Creating dataset {{.CDE_FUSEKI_DATASET}}..."
          # Create the default Fuseki dataset 
          curl -X POST \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -H "$AUTH_HEADER" \
            -d "dbName={{.CDE_FUSEKI_DATASET}}&dbType=tdb2" \
            "http://localhost:3030/$/datasets"
          
          if [ $? -eq 0 ]; then
            echo "Dataset {{.CDE_FUSEKI_DATASET}} created successfully"
          else
            echo "Failed to create dataset {{.CDE_FUSEKI_DATASET}}"
            exit 1
          fi
        fi

        docker compose -p {{.PARTICIPANT_NAME}} -f {{.TASKFILE_DIR}}/docker-compose.yml down fuseki

  start:
    desc: "Start the cde-server"
    cmds:
      - docker compose -p {{.PARTICIPANT_NAME}} -f {{.TASKFILE_DIR}}/docker-compose.yml up -d --wait
  
  stop:
    desc: "Stop the cde-server"
    silent: true
    cmds:
      - docker compose -p {{.PARTICIPANT_NAME}} -f {{.TASKFILE_DIR}}/docker-compose.yml  down

  config:
    silent: true
    desc: "Config the cde-server"
    cmds:
      - docker compose -p {{.PARTICIPANT_NAME}} -f {{.TASKFILE_DIR}}/docker-compose.yml pull --ignore-pull-failures --quiet --policy always
  

  upgrade:
    desc: "Upgrade the cde"
    silent: true
    cmds:
      - docker compose -p {{.PARTICIPANT_NAME}} -f {{.TASKFILE_DIR}}/docker-compose.yml pull --ignore-pull-failures --quiet --policy always

  reset:
    desc: "Reset the cde-configuration"
    cmds:
      - >
      - docker compose -p {{.PARTICIPANT_NAME}} -f {{.TASKFILE_DIR}}/docker-compose.yml  down
      - docker volume rm {{.PARTICIPANT_NAME}}_fuseki-data || true
      - docker volume rm {{.PARTICIPANT_NAME}}_influxdb-data || true

  upload-test-dataset:
    desc: "Upload test dataset_A1.json to the CDE via internal API on port 5000"
    dir: '{{.TASKFILE_DIR}}'
    cmds:
      - |
        # Check if CDE is running
        if curl -sf http://localhost:5000/api/dataset > /dev/null; then
          echo "CDE is running. Proceeding to upload dataset..."
          curl -X POST \
            -F "file=@dataset_A1.json" \
            http://localhost:5000/api/dataset
        else
          echo "CDE is not running on port 5000. Aborting upload."
          exit 1
        fi

