#-------------------------------------------------------------------
# authors     [ Radhouene AZZABI ]
# contacts    [ azzabi.radhouene@cea.fr ]
# created     2024/10-15T12:12:24
# modified    2024/10-15T12:12:24
# version     1.0.0
#-------------------------------------------------------------------

version: "3"

#dotenv: ['../.env'] # uncomment if you want to test tasks localy

tasks:
  start:
    desc: "Start Reverse Proxy"
    deps:
      - config
    cmds:
      - docker compose -p {{.PARTICIPANT_NAME}} up caddy -d --wait
  
  restart:
    desc: "Restart Reverse Proxy"
    deps:
      - config
    cmds:
      - docker compose -p {{.PARTICIPANT_NAME}} restart caddy

  stop:
    desc: "Stop Reverse Proxy"
    cmds:
        - docker compose -p {{.PARTICIPANT_NAME}} down caddy
  
  config:
    dir: '{{.PROXY_FOLDER}}/caddy/conf.d'
    cmds:
      - envsubst < participant.caddy.tmpl > {{.PARTICIPANT_NAME}}.caddy