services:
  credentials-api:
    image: docker.io/agmangas/datacellar-cli:v0.3.1
    container_name: ${PARTICIPANT_NAME}.credentials-api
    restart: unless-stopped
    command: datacellar serve-api --port 8080
    volumes:
      - ${CREDENTIALS_FOLDER}:/credentials
      - ${CERT_FOLDER}:/certs
      - ${WALLET_FOLDER}/waltid/data:/waltid
    # ports:
    #   - 8080:8080
    environment:
      CREDENTIALS_MANAGER_API: "http://credentials-api:8080/api/v1"
      DATACELLAR_API_BASE_URL: ${DATACELLAR_API_BASE_URL}
      WALLET_API_BASE_URL: ${WALLET_API_BASE_URL}
      WALLET_USER_NAME: ${WALLET_USER_NAME}
      WALLET_USER_EMAIL: ${WALLET_USER_EMAIL}
      WALLET_USER_PASSWORD: ${WALLET_USER_PASSWORD}
      DID_WEB_DOMAIN: ${DID_WEB_DOMAIN}
      ISSUER_API_KEY: ${ISSUER_API_KEY}
    networks:
      - datacellar

networks:
  datacellar:
    external: true
    name: datacellar_network
