---
#-------------------------------------------------------------------
# authors     [ Radhouene AZZABI ]
# contacts    [ azzabi.radhouene@cea.fr ]
# created     2024/10-15T12:12:24
# modified    2024/10-15T12:12:24
# version     1.0.0
#-------------------------------------------------------------------

version: "3"

#dotenv: ['../.env'] # uncomment if you want to test tasks localy

tasks:
  start-api:
    desc: "Start Credentials Manager API"
    dir: "{{.CREDENTIALS_MANAGER_FOLDER}}"
    preconditions:
      - test -f docker-compose.yml
    cmds:
      - docker compose -p {{.PARTICIPANT_NAME}} up credentials-api --wait

  stop-api:
    desc: "Stop Credentials Manager"
    dir: "{{.CREDENTIALS_MANAGER_FOLDER}}"
    preconditions:
      - test docker-compose.yml
    cmds:
      - docker compose -p {{.PARTICIPANT_NAME}} stop credentials-api

  provision-wallet:
    silent: true
    desc: "Provision Wallet"
    deps:
      - start-api
    dir: "{{.CREDENTIALS_MANAGER_FOLDER}}"
    preconditions:
      - test -f docker-compose.yml
      - test -f {{.CERT_FOLDER}}/{{.DID_WEB_DOMAIN}}.key
      - test -f {{.CERT_FOLDER}}/{{.DID_WEB_DOMAIN}}.crt
    cmds:
      - echo "Provisioning participant {{.PARTICIPANT_NAME}} wallet"
      - >
        docker exec -it {{.PARTICIPANT_NAME}}.credentials-api
        datacellar provision-wallet

  create-legalparticipant:
    silent: true
    desc: "Create a legal participant with the provided legal name, VAT ID, and country subdivision code"
    deps:
      - start-api
    dir: "{{.CREDENTIALS_MANAGER_FOLDER}}"
    cmds:
      - >
        read -p "Enter legal name (CEA): " legalname &&
        legalname=${legalname:-CEA} &&
        read -p "Enter VAT ID (FR43775685019): " vatid &&
        vatid=${vatid:-FR43775685019} &&
        read -p "Enter country subdivision code (FR-OCC): " subdivision &&
        subdivision=${subdivision:-FR-OCC} &&
        echo "Creating legal participant: legalName=$legalname, vatID=$vatid, CountrySubdivisionCode=$subdivision" &&
        docker exec -it {{.PARTICIPANT_NAME}}.credentials-api
        datacellar create-legal-participant --participant-legal-name=$legalname --participant-vat-id=$vatid --participant-country-subdivision-code=$subdivision

  # register-legalparticipant-catalogue:
  #   desc: "Register a legal participant to the global catalogue"
  #   deps:
  #     - start-api
  #   silent: true
  #   dir: "{{.CREDENTIALS_MANAGER_FOLDER}}"
  #   cmds:
  #     - |
  #       read -p "VP Legal Participant (url or id): " legalparticipant_id
  #       legalparticipant_id=${legalparticipant_id:-}

  #       docker exec -it {{.PARTICIPANT_NAME}}.credentials-api \
  #         bash -c "\
  #         LEGAL_PARTICIPANT_ID=$legalparticipant_id \
  #         python3 register_participant_to_catalogue.py"
