---
#-------------------------------------------------------------------
# authors     [ Radhouene AZZABI ]
# contacts    [ azzabi.radhouene@cea.fr ]
# created     2024/10-15T12:12:24
# modified    2024/10-15T12:12:24
# version     1.0.0
#-------------------------------------------------------------------

version: "3"

#dotenv: ['../.env'] # uncomment if you want to test tasks localy

tasks:
  start-api:
    desc: "Start Credentials Manager API"
    silent: true
    preconditions:
      - test -f {{.TASKFILE_DIR}}/docker-compose.yml
    cmds:
      - docker compose -p {{.PARTICIPANT_NAME}} -f {{.TASKFILE_DIR}}/docker-compose.yml up credentials-api --wait

  stop-api:
    desc: "Stop Credentials Manager"
    silent: true
    preconditions:
      - test -f {{.TASKFILE_DIR}}/docker-compose.yml
    cmds:
      - docker compose -p {{.PARTICIPANT_NAME}} -f {{.TASKFILE_DIR}}/docker-compose.yml down credentials-api

  provision-wallet:
    silent: true
    desc: "Provision Wallet"
    deps:
      - start-api
    preconditions:
      - test -f {{.TASKFILE_DIR}}/docker-compose.yml
      - test -f {{.CERT_FOLDER}}/{{.DID_WEB_DOMAIN}}.key
      - test -f {{.CERT_FOLDER}}/{{.DID_WEB_DOMAIN}}.crt
    cmds:
      - echo "Provisioning participant {{.PARTICIPANT_NAME}} wallet"
      - >
        docker exec -it {{.PARTICIPANT_NAME}}.credentials-api datacellar provision-wallet

  create-legalparticipant:
    silent: true
    desc: "Create a legal participant with the provided legal name, VAT ID, and country subdivision code"
    deps:
      - start-api
    cmds:
      - |
        if [ -f .env.local ]; then
          echo "Found existing .env.local:"
          cat .env.local
          read -p "Do you want to reuse these values? [Y/n]: " reuse
          reuse=${reuse:-Y}
        else
          reuse="n"
        fi

        if [ "$reuse" = "n" ] || [ "$reuse" = "N" ]; then
          read -p "Enter legal name (CEA): " legalname
          legalname=${legalname:-CEA}
          read -p "Enter VAT ID (FR43775685019): " vatid
          vatid=${vatid:-FR43775685019}
          read -p "Enter country subdivision code (FR-OCC): " subdivision
          subdivision=${subdivision:-FR-OCC}
          echo "LEGAL_NAME=$legalname" > .env.local
          echo "VAT_ID=$vatid" >> .env.local
          echo "SUBDIVISION=$subdivision" >> .env.local
        fi

        # Load values
        source .env.local

        echo "Using: legalName=$LEGAL_NAME, vatID=$VAT_ID, CountrySubdivisionCode=$SUBDIVISION"

        docker exec -it {{.PARTICIPANT_NAME}}.credentials-api \
          datacellar create-legal-participant \
            --participant-legal-name=$LEGAL_NAME \
            --participant-vat-id=$VAT_ID \
            --participant-country-subdivision-code=$SUBDIVISION

  upgrade:
    desc: "Upgrade the credentials-manager"
    silent: true
    cmds:
      - docker compose -p {{.PARTICIPANT_NAME}} -f {{.TASKFILE_DIR}}/docker-compose.yml pull --ignore-pull-failures --quiet --policy always
  
