#-------------------------------------------------------------------
# authors     [ Radhouene AZZABI ]
# contacts    [ azzabi.radhouene@cea.fr ]
# created     2024/10-15T12:12:24
# modified    2024/10-15T12:12:24
# version     1.0.0
#-------------------------------------------------------------------

version: "3"


#dotenv: ['../.env'] # uncomment if you want to test tasks localy

tasks:
  
  # Credentials Manager API
  start-api:
    desc: "Start Credentials Manager API"
    dir: '{{.CREDENTIALS_MANAGER_FOLDER}}'
    preconditions:
      - test -f docker-compose.yml
    cmds:
      - docker compose up credentials-api --wait
    
  stop-api:
    desc: "Stop Credentials Manager"
    dir: '{{.CREDENTIALS_MANAGER_FOLDER}}'
    preconditions:
      - test docker-compose.yml
    cmds:
      - docker compose stop credentials-api
  
  provision-wallet:
    desc: "Provision Wallet"
    dir: '{{.CREDENTIALS_MANAGER_FOLDER}}'
    preconditions:
      - test -f docker-compose.yml
      - test -f {{.CERT_FOLDER}}/{{.DID_WEB_DOMAIN}}.key
      - test -f {{.CERT_FOLDER}}/{{.DID_WEB_DOMAIN}}.crt
    cmds:
      - docker compose up provision-wallet --wait
  

  # # config-certs:
  # #   vars: 
  # #     DIR_PATH: '{{.USER_WORKING_DIR}}'
  # #     CERTS_PATH: '{{.USER_WORKING_DIR}}/store/certs'
  # #   dir: '{{.DIR_PATH}}'
  # #   dotenv: ['{{.DIR_PATH}}/.env']
  # #   cmds:
  # #     - sudo cp {{.CERTS_PATH}}/{{.DID_WEB_DOMAIN}}/* {{.CREDENTIALS_MANAGER_PATH}}/data/vc/x5u.pem
  # #     - sudo cp {{.CERTS_PATH}}/{{.DID_WEB_DOMAIN}}/{{.DID_WEB_DOMAIN}}.crt {{.CREDENTIALS_MANAGER_PATH}}/data/vc/x5u.pem
  # #     - sudo chown {{.USER}}:{{.USER}} {{.CREDENTIALS_MANAGER_PATH}}/data/vc/x5u.pem
  # #     - curl -s https://letsencrypt.org/certs/isrgrootx1.pem >> {{.CREDENTIALS_MANAGER_PATH}}/data/vc/x5u.pem


  # # Credentials Manager Webui
  # start-webui:
  #   desc: "Start Credentials Manager Webui"
  #   deps:
  #     - config-credentials-manager
  #   vars: 
  #     DIR_PATH: '{{.USER_WORKING_DIR}}/credentials-manager'
  #   dir: '{{.DIR_PATH}}'
  #   dotenv: ['{{.DIR_PATH}}/.env']
  #   preconditions:
  #     - test -f docker-compose.yml
  #   cmds:
  #     - docker compose up --wait
    
  # stop-webui:
  #   desc: "Stop Credentials Manager Webui"
  #   vars: 
  #     DIR_PATH: '{{.USER_WORKING_DIR}}/credentials-manager'
  #   dir: '{{.DIR_PATH}}'
  #   dotenv: ['{{.DIR_PATH}}/.env']
  #   preconditions:
  #     - test -f docker-compose.yml
  #   cmds:
  #     - docker compose down
