services:
  did-server:
    image: nginx
    container_name: ${PARTICIPANT_NAME}.did-server
    restart: unless-stopped
    volumes:
      - ${CREDENTIALS_FOLDER}/.well-known:/usr/share/nginx/html/.well-known
      - ${CREDENTIALS_FOLDER}/vc:/usr/share/nginx/html/vc
      - ${CREDENTIALS_FOLDER}/vp:/usr/share/nginx/html/vp
    # ports:
    #   - "80:80"
    networks:
      - datacellar

networks:
  datacellar:
    external: true
    name: datacellar_network
